# Generated by Django 5.2.14 on 2026-05-08 12:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('widget_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='ID виджета')),
                ('name', models.CharField(max_length=255, verbose_name='Название бота')),
                ('theme_color', models.CharField(default='#000000', max_length=7, verbose_name='Цвет темы')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bots', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Бот',
                'verbose_name_plural': 'Боты',
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('visitor_id', models.CharField(max_length=255, verbose_name='ID посетителя (сессии)')),
                ('contact_info', models.CharField(blank=True, max_length=255, verbose_name='Контактные данные')),
                ('chat_history', models.JSONField(default=list, verbose_name='История диалога')),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='bots.bot', verbose_name='Бот')),
            ],
            options={
                'verbose_name': 'Лид',
                'verbose_name_plural': 'Лиды',
            },
        ),
        migrations.CreateModel(
            name='ScenarioNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('step_type', models.CharField(choices=[('message', 'Сообщение'), ('phone_collection', 'Сбор номера телефона'), ('button_choice', 'Выбор кнопкой')], max_length=20, verbose_name='Тип шага')),
                ('content', models.TextField(verbose_name='Контент сообщения')),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='bots.bot', verbose_name='Бот')),
            ],
            options={
                'verbose_name': 'Узел сценария',
                'verbose_name_plural': 'Узлы сценария',
            },
        ),
    ]
