# Generated by Django 5.2.14 on 2026-05-10 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='contact_info',
        ),
        migrations.AddField(
            model_name='lead',
            name='data',
            field=models.JSONField(blank=True, default=dict, verbose_name='Собранные данные'),
        ),
        migrations.AddField(
            model_name='scenarionode',
            name='settings',
            field=models.JSONField(blank=True, default=dict, verbose_name='Настройки (кнопки, валидация)'),
        ),
        migrations.AlterField(
            model_name='scenarionode',
            name='step_type',
            field=models.CharField(choices=[('message', 'Сообщение'), ('question', 'Свободный ввод'), ('button_choice', 'Выбор кнопкой'), ('form', 'Форма (Email/Phone)')], max_length=20, verbose_name='Тип шага'),
        ),
    ]
