# Generated by Django 5.2.14 on 2026-05-12 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0003_remove_lead_chat_history_chatmessage_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='bot',
            name='allowed_domain',
            field=models.CharField(blank=True, help_text='Например: example.com', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='bot_text',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='bots.lead'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='node',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bots.scenarionode'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='user_answer',
            field=models.TextField(blank=True),
        ),
    ]
