# Generated by Django 5.2.14 on 2026-05-12 15:06

import bots.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0004_remove_chatmessage_updated_at_bot_allowed_domain_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='widget_id',
            field=models.CharField(default=bots.models.generate_widget_id, editable=False, max_length=20, unique=True, verbose_name='ID виджета'),
        ),
    ]
